### ISSUE TITLE
Replying from Matrix to Telegram doesn't ping the user

### ISSUE THREAD

**Issue by NichopeJustPassing** [SijmenSchoon/telematrix#28]
When somebody on Matrix replies to a user that is on Telegram, the reply addresses the Telegram user by "nickname (Telegram):", so the Telegram user is not pinged and may miss the reply.
I believe that if the Telegram room saw "@nickname" instead of "nickname (Telegram):", the user to which the reply goes would be notified about it.

**Comment by almereyda** [comment]
Did you already try sending a manual `@someone` reply into a bridged room and check for its effects?

**Comment by Mikaela** [comment]
> Did you already try sending a manual `@someone` reply into a bridged room and check for its effects?

How do we know what to put in place of `@someone` when we only receive Telegram firstname and lastname and not the actual `username` that is used for mentioning?

**Comment by SijmenSchoon** [comment]
This can be fixed by the mention API, as proposed by #36
