### ISSUE TITLE
Riot to Telegram not working

### ISSUE THREAD

**Issue by evok3d** [SijmenSchoon/telematrix#38]
Hi,

This seems to work for me from telegram to riot, but messages are not going from riot to telegram. Any advice or is this an issue?

**Comment by elopio** [comment]
This is happening to me too.
@evok3d is your room encrypted? Mine is.

**Comment by SijmenSchoon** [comment]
Telematrix does not support end-to-end encrypted rooms.

**Comment by evok3d** [comment]
screenshot of the settings:
https://prnt.sc/ghwnl0

it is not encrypted to be honest. I am using t2bot.io implementation. If you have a different solution, please do let me know.

Thank you for your help.

**Comment by SijmenSchoon** [comment]
Have you had any luck bridging your channel/group? I've just created my own t2bot link (haven't really had the time and energy to maintain my own homeserver) and it seems to work fine
