### ISSUE TITLE
Unknown telegram chat <aiotg.chat.Chat object at 0xREDACTED>

### ISSUE THREAD

**Issue by pstn** [SijmenSchoon/telematrix#47]
I've tried setting up telematrix on my homeserver, but it's not working.
I can talk to the bot via Telegram, but every time I say something other than ```/alias``` in chat, I get the above message with the Channel name afterwards. Also I get a lot of Messages like
```
discarded event of age 25136777942
discarded event of age 25136730964
discarded event of age 25136627822
discarded event of age 735996753
discarded event of age 735978815
discarded event of age 735973379
discarded event of age 25136463459
discarded event of age 25136449829
discarded event of age 725606408
discarded event of age 25136524428
discarded event of age 725299739
discarded event of age 25136294025
discarded event of age 25136281056
```
and
```
REDACTED:matrix.org: <@REDACTED:im.nostrodomo.tk> m.room.message
REDACTED:matrix.org isn't linked!
REDACTED:matrix.org: <@REDACTED:im.nostrodomo.tk> m.room.message
REDACTED:matrix.org isn't linked!
REDACTED:matrix.org: <@REDACTED:matrix.org> m.room.message
REDACTED:matrix.org isn't linked!
REDACTED:matrix.org: <@REDACTED:cervoi.se> m.room.member
REDACTED:matrix.org isn't linked!
```
Also I don't get any members of the telegram chat joining my rooms that I named according to the ```/help``` output.
My sqlite database exists, but there are no entries in the tables at any time, I think (at least I never saw one and the file size seems to stay constant).

I'm a bit stuck because I don't know how to get any further debugging information and don't know what's wrong. I'd be glad for any help.

**Comment by SijmenSchoon** [comment]
Have you added the alias from /alias to the Matrix chat?

**Comment by pstn** [comment]
Yes, I did. As a room name, right?

**Comment by SijmenSchoon** [comment]
And is the chat set to invite only? Telematrix currently doesn't support
these

**Comment by pstn** [comment]
The Chat is set to ```Anyone who knows the room's link, apart from guests```

**Comment by pstn** [comment]
asconfig.yaml:
```url: "http://localhost:5001"

as_token: "aREDACTED"
hs_token: "SREDACTED"
id: "telematrix"

sender_localpart: telegram
namespaces:
    users:
        - exclusive: true
          regex: '@telegram_.*'
    rooms: []
    aliases:
        - exclusive: false
          regex: '#telegram_.*'
```
config.json:
```
{
    "tokens": {
        "hs": "SREDACTED",
        "as": "aREDACTED",
        "telegram": "REDACTED"
    },

    "hosts": {
        "internal": "https://127.0.0.1:8448/",
        "external": "https://matrix.xndr.de/",
        "bare": "xndr.de"
    },

    "user_id_format": "@telegram_{}:xndr.de",
    "db_url": "sqlite:////var/lib/telematrix/sqlite.db",

    "as_port": 5001
}

Any obvious mistakes?

**Comment by pstn** [comment]
I think the problem was that the bot doesn't work with a synapse that only listens to https on localhost. I reconfigured my synapse because of different reasons and now it is working.
